workflows:
  flutter-workflow:
    name: Flutter Build (Android & iOS)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Clean build
        script: flutter clean

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build iOS
        script: |
          cd ios
          rm -rf Podfile.lock Pods
          pod install --repo-update
          cd ..
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
