platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

end
