platform :ios, '11.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_application_path = '../..'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)
end